---
title: "PCA"
author: "J. Meyer"
date: "2024-12-12"
output: html_document
---

```{r setup, include=FALSE}
library(phyloseq)
library(CoDaSeq)
library(ggplot2)
library(cowplot)
library(tibble)
library(dplyr)
library(vegan)
library(pairwiseAdonis)
library(rstatix)
writeLines(capture.output(sessionInfo()), "sessionInfo.txt")
```

## Perform center-log-ratio transformation on ASVs and calculate Aitchison Distance and principal components


```{r, echo=FALSE}

otu <- read.table("Tent_Expm_silva_nochloronomito_otu_table.txt",sep="\t",header=TRUE, row.names=1)
taxon <- read.table("Tent_Expm_silva_nochloronomito_taxa_table.txt",sep="\t",header=TRUE,row.names=1)
samples<-read.table("Tent_Expm_metadata.txt",sep="\t",header=T,row.names=1)
OTU = otu_table(otu, taxa_are_rows=FALSE)
taxon<-as.matrix(taxon)
TAX = tax_table(taxon)
sampledata = sample_data(samples)
ps <- phyloseq(otu_table(otu, taxa_are_rows=FALSE), 
               sample_data(samples), 
               tax_table(taxon))
ps # 11845 taxa and 96 samples

# remove low abundance taxa
ps2<-filter_taxa(ps, function(x) mean(x) >1, TRUE) 
ps2 # 1145 taxa and 96 samples
otu = as(otu_table(ps2), "matrix")
taxon = as(tax_table(ps2), "matrix")
write.table(taxon,"Tent_Expm_silva_nochloronomito_taxa_table_ps2.txt",sep="\t",col.names=NA)
write.table(otu, "Tent_Expm_silva_nochloronomito_otu_table_ps2.txt",sep="\t",col.names=NA)

# clear and read back in prepared data; analysis is performed on the otu table (not the phyloseq object)
otu <- read.table("Tent_Expm_silva_nochloronomito_otu_table_ps2.txt",sep="\t",header=TRUE, row.names=1)
taxon <- read.table("Tent_Expm_silva_nochloronomito_taxa_table_ps2.txt",sep="\t",header=TRUE,row.names=1)
samples<-read.table("Tent_Expm_metadata.txt",sep="\t",header=T,row.names=1)
OTU = otu_table(otu, taxa_are_rows=FALSE)
taxon<-as.matrix(taxon)
TAX = tax_table(taxon)
sampledata = sample_data(samples)
ps2 <- phyloseq(otu_table(otu, taxa_are_rows=FALSE), 
               sample_data(samples), 
               tax_table(taxon))
ps2 # 1145 taxa and 96 samples
```

### ALPHA DIVERSITY
1. Plot alpha diversity measures

```{r, echo=FALSE}
# calculate alpha diversity measures with phyloseq wrapper
alpha.diversity <- estimate_richness(ps2, measures = c("Observed","Shannon","Simpson"))

# combine alpha diversity measures with sample metadata
alpha.diversity <- tibble::rownames_to_column(alpha.diversity, "sample")
samples <- tibble::rownames_to_column(samples, "sample")
alpha_meta <- merge(alpha.diversity, samples, by="sample", all=TRUE)

# set asethetics
alpha_meta$Timepoint<-factor(alpha_meta$Timepoint,levels=c("before","after","recovery"))
alpha_meta$Treatment<-factor(alpha_meta$Treatment,levels=c("fully closed","partially closed","open"))
cols1<-c("before"="#009E73","after"="#CC79A7","open"="#999999") #colorblind friendly palette
cols2<-c("fully closed"="#D55E00","partially closed"="#0072B2","open"="#56B4E9") #colorblind friendly palette

# plot box and whiskers with points on top

obs <- ggplot(alpha_meta,aes(x=Timepoint,y=Observed,color=Timepoint))+
  geom_boxplot(outlier.shape=NA)+
  geom_jitter(aes(color=Treatment))+
  facet_grid(Species~.)+
  theme(strip.text.y=element_text(face="bold.italic"))+
  theme(legend.position="none")+
  theme(axis.title.x=element_blank())+
  theme(text=element_text(size=14,face="bold"))+
  scale_color_manual(values=cols2)
obs

shan <- ggplot(alpha_meta,aes(x=Timepoint,y=Shannon,color=Timepoint))+
  geom_boxplot(outlier.shape=NA)+
  geom_jitter(aes(color=Treatment))+
  facet_grid(Species~.)+
  theme(strip.text.y=element_text(face="bold.italic"))+
  theme(legend.position="none")+
  theme(axis.title.x=element_blank())+
  theme(text=element_text(size=14,face="bold"))+
  scale_color_manual(values=cols2)
shan

simp <- ggplot(alpha_meta,aes(x=Timepoint,y=Simpson,color=Timepoint))+
  geom_boxplot(outlier.shape=NA)+
  geom_jitter(aes(color=Treatment))+
  facet_grid(Species~.)+
  theme(strip.text.y=element_text(face="bold.italic"))+
  theme(legend.position="none")+
  theme(axis.title.x=element_blank())+
  theme(text=element_text(size=14,face="bold"))+
  scale_color_manual(values=cols2)
simp

pdf("AlphaDiversity_96.pdf", bg ="white", width=8.5)
plot_grid(obs,shan,simp, labels=c("A","B","C"), ncol=3)
dev.off()

# print plot for the legend
pdf("Alpha+legend.pdf", bg ="white", width=8.5)
obs2 <- ggplot(alpha_meta,aes(x=Timepoint,y=Observed,color=Timepoint))+
  geom_boxplot(outlier.shape=NA)+
  geom_jitter(aes(color=Treatment))+
  facet_grid(Species~.)+
  theme(strip.text.y=element_text(face="bold.italic"))+
  theme(legend.position="bottom")+
  theme(axis.title.x=element_blank())+
  theme(text=element_text(size=14,face="bold"))+
  theme(legend.title=element_blank())+
  scale_color_manual(values=cols2)
obs2
dev.off()

```

### ALPHA DIVERSITY
2. Test statistical differences in alpha diversity across time points and treatments

```{r, echo=FALSE}
# Test for statistical differences in alpha diversity between time points - test within species
alphaA <- alpha_meta %>% filter(Species =='Agaricia tenuifolia')
alphaS <- alpha_meta %>% filter(Species =='Siderastrea siderea')

### Agaricia, all samples
# First test for normality using Shapiro test. If the value of p is equal to or less than 0.05, 
# then the hypothesis of normality will be rejected. 
shapiro.test(alphaA$Observed) # p-value = 8.239e-09
shapiro.test(alphaA$Shannon) # p-value = 0.2619
shapiro.test(alphaA$Simpson) # p-value = 0.0006831
# Only Shannon follows normality

# 2-way ANOVA test for normally distributed diversity measure - Shannon diversity
anova1 <- aov(Shannon ~ Timepoint + Treatment + Timepoint:Treatment, alphaA) 
summary(anova1) 
TukeyHSD(anova1)

# 2-way ANOVA on ranked data for non-normally distributed diversity measures - Observed, Simpson
anova2 <- aov(rank(Observed) ~ Timepoint + Treatment + Timepoint:Treatment, alphaA) 
summary(anova2) 
TukeyHSD(anova2)

anova3 <- aov(rank(Simpson) ~ Timepoint + Treatment + Timepoint:Treatment, alphaA) 
summary(anova3) 
TukeyHSD(anova3)


### Siderastrea, all samples
shapiro.test(alphaS$Observed) # p-value = 0.7403
shapiro.test(alphaS$Shannon) # p-value = 0.6582
shapiro.test(alphaS$Simpson) # p-value = 3.318e-05
# Both Observed and Shannon are normally distributed

# 2-way ANOVA test for normally distributed diversity measures - Observed, Shannon
anova4 <- aov(Observed ~ Timepoint + Treatment + Timepoint:Treatment, alphaS) 
summary(anova4) 
TukeyHSD(anova4)

anova5 <- aov(Shannon ~ Timepoint + Treatment + Timepoint:Treatment, alphaS) 
summary(anova5) 
TukeyHSD(anova5)

# 2-way ANOVA on ranked data for non-normally distributed diversity measure - Simpson
anova6 <- aov(rank(Simpson) ~ Timepoint + Treatment + Timepoint:Treatment, alphaS) 
summary(anova3) 
TukeyHSD(anova3)

```


### BETA DIVERSITY


```{r, echo=FALSE}
# CALCULATE AITCHISON DISTANCE
# First, replace 0 values with an estimate (because normalization is taking log, can't have 0)
# Also transposing here, need samples as rows
d.czm <- cmultRepl(t(otu), method="CZM", label=0, z.warning=1)
# Perform the center-log-ratio (CLR) transformation 
d.clr <- codaSeq.clr(d.czm)
# transpose matrix of CLR transformed data for ordination and dendrogram
E.clr <- t(d.clr)
# plot compositional PCA biplot (perform a singular value decomposition)
d.pcx <- prcomp(E.clr)
# calculate percent variance explained for the axis labels
pc1 <- round(d.pcx$sdev[1]^2/sum(d.pcx$sdev^2),2)
pc2 <- round(d.pcx$sdev[2]^2/sum(d.pcx$sdev^2),2)
xlab <- paste("PC1: ", pc1, sep="")
ylab <- paste("PC2: ", pc2, sep="")
#biplot(d.pcx, cex=c(0.6,0.4), var.axes=F,scale=1, xlab=xlab, ylab=ylab)
summary(d.pcx)
str(d.pcx)
screeplot(d.pcx)

# replot PCA with ggplot2 (showing samples only)
df_out <- as.data.frame(d.pcx$x)
theme_set(theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank()))
cols<-c("fully closed"="#D55E00","partially closed"="#0072B2","open"="#56B4E9") #colorblind friendly palette
samples$Treatment<-factor(samples$Treatment,levels=c("fully closed","partially closed","open"))
samples$Timepoint<-factor(samples$Timepoint,levels=c("before","after","recovery"))

pdf("PCA_96.pdf",bg ="white",width = 8.5)
p<-ggplot(df_out,aes(x=PC1,y=PC2,color=samples$Treatment,shape=samples$Species))
p<-p+geom_point(size=2)+
  theme(axis.title = element_text(size=14))+
  theme(axis.text=element_text(size=12))+
  theme(legend.title = element_text(size=14))+
  theme(legend.text = element_text(size=12))+
  theme(strip.text.x = element_text(size=12))+
  scale_color_manual(values=cols)+
  guides(fill = guide_legend(override.aes=list(shape=21)))+
  facet_grid(~samples$Timepoint)
p + labs(x=xlab, y=ylab, color="Treatment",shape="Coral species") +coord_fixed()
dev.off()


pdf("PCA_96_facet.pdf",bg ="white",width = 8.5)
p<-ggplot(df_out,aes(x=PC1,y=PC2,color=samples$Treatment))
p<-p+geom_point(size=2)+
  theme(axis.title = element_text(size=14))+
  theme(axis.text=element_text(size=12))+
  theme(legend.title = element_text(size=14))+
  theme(legend.text = element_text(size=12))+
  theme(strip.text.x = element_text(size=12))+
  theme(strip.text.y = element_text(size=12,face="italic"))+
  scale_color_manual(values=cols)+
  guides(fill = guide_legend(override.aes=list(shape=21)))+
  facet_grid(samples$Species~samples$Timepoint)
p + labs(x=xlab, y=ylab, color="Treatment") +coord_fixed()
dev.off()


####### Perform permanova using Aitchison distance
dist.clr <- dist(E.clr)
perm<-adonis2(dist.clr~Treatment*Timepoint*Species,as(sample_data(ps2),"data.frame"))
print(perm)
perm2<-pairwise.adonis2(dist.clr~Treatment*Timepoint/Species,as(sample_data(ps2),"data.frame"), strata='Species')
print(perm2)

```

